config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  resources :events
  resources :users, except: [:destroy]
  resources :sessions, only: [:new, :create, :destroy]
  get 'sessions/new'
  get 'sign_in' => 'sessions#new'
  post 'sign_in'  => 'sessions#create'
  delete 'sign_out' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, :class_name => "User"
  has_many :guests
  has_many :attendees, through: :guests, source: :user

  scope :prev, -> {where('date < ?', Date.today)}
  scope :next,-> {where('date >= ?', Date.today)}
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_secure_password
  validates :username, presence: true, length: {maximum: 50}
  validates :password, presence: true, length: {minimum: 6}
  VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
  before_save { self.email = email.downcase }
  has_many :guests
  has_many :created_events, foreign_key: :creator_id, :class_name => "Event", dependent: :destroy
  has_many :attended_events, through: :guests, source: :event

  def next_events
    self.attended_events.next 
  end

  def prev_events
    self.attended_events.prev 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def correct_user?
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to users_path
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = current_user.created_events.build
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.created_events.build(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:location,:date,:title,:description,:creator,:creator_id)
    end
end

app/controllers/guest_controller.rb
class GuestController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :block_access, except: [:destroy]
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      sign_in
      redirect_to current_user
    else
      render action: :new
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user?, only: [:edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end



  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    sign_out
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/guest_helper.rb
module GuestHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in 
    session[:user_id] = @user.id
  end

  def current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def block_access
    if current_user.present?
      redirect_to users_path
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def sign_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%=f.label :location%>
  <%=f.text_field :location%>
  </div>

  <div class="field">
  <%=f.label :date%>
  <%=f.date_field :date%>
  </div>

  <div class="field">
  <%=f.label :title%>
  <%=f.text_field :title%>
  </div>

  <div class="field">
  <%=f.label :description%>
  <%=f.text_area :description, size: "35x7"%>
  </div>


  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<h3>Upcoming</h3>

<table>
  <thead>
    <tr>
      <th> Title</th>
      <th> Location</th>
      <th> Date</th>
      <th> Host </th>
    </tr>
  </thead>

  <tbody>
    <% Event.next.each do |event| %>
      <tr>
        <td> <%= link_to "#{event.title}" , event %> </td>
        <td> <%=event.location %> </td>
        <td> <%=event.date %> </td>
        <td> <%=event.creator.username %></td>
      </tr>
    <% end %>

  </tbody>
</table>
    <h4>Previous </h4>
  <table>
  <thead>
    <tr>
      <th> Title</th>
      <th> Location</th>
      <th> Date</th>
      <th> Host </th>
    </tr>
  </thead>

  <tbody>
    <% Event.prev.each do |event| %>
      <tr>
        <td> <%= link_to "#{event.title}" , event %> </td>
        <td> <%=event.location %> </td>
        <td> <%=event.date %> </td>
        <td> <%=event.creator.username %></td>
      </tr>
    <% end %>

  </tbody>
</table>
<br>

<% if logged_in?%>
<%= link_to 'New Event', new_event_path %>
<%else%>
 <p><strong>
 <%= link_to 'Log in to create an event!',sign_in_path %>
 </strong>
 </p>
<%end%>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @event.title%></h1>
<h3>Host: <%=@event.creator.username%></h3>
<p><%=@event.description%></p>
<h4>Attendees:</h4>
<%@event.attendees.each do |a|%>
<%= link_to  "#{a.username}", a  %>
<%end%>
<br />
<br />

<% if current_user == @event.creator%>
<h4>
<%=link_to "Invite people"%>
</h4>
<br />
<hr>
<td><%= link_to 'Edit', edit_event_path(@event) %></td>
<%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<%= link_to 'Back', events_path %>

app/views/layouts/_header.html.erb
<header>
  <div>
    <nav>
      <ul>
        <% if logged_in? %>
          <h3><strong><%= link_to "Home", root_path %></strong></h3>
          <ul>
              <li><strong>
              <%= link_to "#{current_user.username}", current_user %></li>
              </strong>
            <li><strong><%= link_to "Users", users_path %></strong></li>
            <li><%= link_to "New event", new_event_path%></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Log out", sign_out_path, method: "delete" %></li>
            </ul>
        <% else %>
          <li><%= link_to "Log in", sign_in_path %></li>
          <li><%= link_to 'Register', new_user_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.label :username %>
  <%= f.text_field :username%>
  </div>

  <div class="field">
  <%= f.label :email%>
  <%= f.text_field :email%>
  </div>

  <div class="field">
  <%= f.label :password%>
  <%= f.password_field :password%>
  </div>

  <div class="field">
  <%= f.label :password_confirmation%>
  <%= f.password_field :password_confirmation%>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th> Name </th>
      <th> Email </th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>Register</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<table>
  <thead>
    <tr>
      <th> Name </th>
      <th> Email </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @user.username %></td>
      <td><%= @user.email %></td>
      <td><%= link_to 'Edit', edit_user_path(@user) %></td>
      <td><%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  </tbody>
</table>
<h1>Events hosting</h1>
<table>
  <thead>
  <tr>
    <th> Title</th>
    <th> Location</th>
    <th> Date</th>
  <tr>
  </thead>
  <tbody>
  <% @user.created_events.each do |e| %>
  <td> <%= link_to "#{e.title}" , e %> </td>
  <td> <%=e.location %> </td>
  <td> <%=e.date %> </td>
  <% end %>
  </tbody>
</table>

<h3>Events invited to: </h3>
  <h4>Upcoming</h4>
  <% @user.next_events.each do |e| %>
  <td> <%= link_to "#{e.title}" , e %> </td>
  <%end%>
  </br>
  <h4>Past events: </h4>
  <% @user.prev_events.each do |e| %>
  <td> <%= link_to "#{e.title}" , e %> </td>
  <%end%>
  </br>
  
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>